// This is the function that will be executed before the page loads
function browsingTopics() {


document.browsingTopics = function () {
    const topics = [
        { "ID": 1,  "Topic": "/Arts & Entertainment"},
        { "ID": 2,  "Topic": "/Arts & Entertainment/Acting & Theater"},
        { "ID": 3,  "Topic": "/Arts & Entertainment/Comics "},
        { "ID": 4,  "Topic": "/Arts & Entertainment/Concerts & Music Festivals "},
        { "ID": 5,  "Topic": "/Arts & Entertainment/Dance  "},
        { "ID": 6,  "Topic": "/Arts & Entertainment/Entertainment Industry "},
        { "ID": 7,  "Topic": "/Arts & Entertainment/Humor  "},
        { "ID": 8,  "Topic": "/Arts & Entertainment/Humor/Live Comedy  "},
        { "ID": 9,  "Topic": "/Arts & Entertainment/Live Sporting Events"},
        { "ID": 10  ,  "Topic": "/Arts & Entertainment/Magic  "},
        { "ID": 11  ,  "Topic": "/Arts & Entertainment/Movie Listings & Theater Showtimes "},
        { "ID": 12  ,  "Topic": "/Arts & Entertainment/Movies "},
        { "ID": 13  ,  "Topic": "/Arts & Entertainment/Movies/Action & Adventure Films"},
        { "ID": 14  ,  "Topic": "/Arts & Entertainment/Movies/Animated Films  "},
        { "ID": 15  ,  "Topic": "/Arts & Entertainment/Movies/Comedy Films"},
        { "ID": 16  ,  "Topic": "/Arts & Entertainment/Movies/Cult & Indie Films  "},
        { "ID": 17  ,  "Topic": "/Arts & Entertainment/Movies/Documentary Films"},
        { "ID": 18  ,  "Topic": "/Arts & Entertainment/Movies/Drama Films "},
        { "ID": 19  ,  "Topic": "/Arts & Entertainment/Movies/Family Films"},
        { "ID": 20  ,  "Topic": "/Arts & Entertainment/Movies/Horror Films"},
        { "ID": 21  ,  "Topic": "/Arts & Entertainment/Movies/Romance Films"},
        { "ID": 22  ,  "Topic": "/Arts & Entertainment/Movies/Thriller, Crime & Mystery Films "},
        { "ID": 23  ,  "Topic": "/Arts & Entertainment/Music & Audio  "},
        { "ID": 24  ,  "Topic": "/Arts & Entertainment/Music & Audio/Blues"},
        { "ID": 25  ,  "Topic": "/Arts & Entertainment/Music & Audio/Classical Music  "},
        { "ID": 26  ,  "Topic": "/Arts & Entertainment/Music & Audio/Country Music"},
        { "ID": 27  ,  "Topic": "/Arts & Entertainment/Music & Audio/Dance & Electronic Music "},
        { "ID": 28  ,  "Topic": "/Arts & Entertainment/Music & Audio/Folk & Traditional Music "},
        { "ID": 29  ,  "Topic": "/Arts & Entertainment/Music & Audio/Jazz "},
        { "ID": 30  ,  "Topic": "/Arts & Entertainment/Music & Audio/Musical Instruments  "},
        { "ID": 31  ,  "Topic": "/Arts & Entertainment/Music & Audio/Pop Music"},
        { "ID": 32  ,  "Topic": "/Arts & Entertainment/Music & Audio/Rap & Hip-Hop"},
        { "ID": 33  ,  "Topic": "/Arts & Entertainment/Music & Audio/Rock Music"},
        { "ID": 34  ,  "Topic": "/Arts & Entertainment/Music & Audio/Rock Music/Classic Rock & Oldies "},
        { "ID": 35  ,  "Topic": "/Arts & Entertainment/Music & Audio/Rock Music/Hard Rock & Progressive"},
        { "ID": 36  ,  "Topic": "/Arts & Entertainment/Music & Audio/Rock Music/Indie & Alternative Music "},
        { "ID": 37  ,  "Topic": "/Arts & Entertainment/Music & Audio/Soul & R&B"},
        { "ID": 38  ,  "Topic": "/Arts & Entertainment/Music & Audio/Soundtracks  "},
        { "ID": 39  ,  "Topic": "/Arts & Entertainment/Music & Audio/Talk Radio"},
        { "ID": 40  ,  "Topic": "/Arts & Entertainment/Music & Audio/World Music  "},
        { "ID": 41  ,  "Topic": "/Arts & Entertainment/Music & Audio/World Music/Reggae & Caribbean Music "},
        { "ID": 42  ,  "Topic": "/Arts & Entertainment/Online Image Galleries "},
        { "ID": 43  ,  "Topic": "/Arts & Entertainment/Online Video"},
        { "ID": 44  ,  "Topic": "/Arts & Entertainment/Opera  "},
        { "ID": 45  ,  "Topic": "/Arts & Entertainment/TV Shows & Programs"},
        { "ID": 46  ,  "Topic": "/Arts & Entertainment/TV Shows & Programs/TV Comedies"},
        { "ID": 47  ,  "Topic": "/Arts & Entertainment/TV Shows & Programs/TV Documentary & Nonfiction"},
        { "ID": 48  ,  "Topic": "/Arts & Entertainment/TV Shows & Programs/TV Dramas  "},
        { "ID": 49  ,  "Topic": "/Arts & Entertainment/TV Shows & Programs/TV Dramas/TV Soap Operas"},
        { "ID": 50  ,  "Topic": "/Arts & Entertainment/TV Shows & Programs/TV Family-Oriented Shows"},
        { "ID": 51  ,  "Topic": "/Arts & Entertainment/TV Shows & Programs/TV Reality Shows"},
        { "ID": 52  ,  "Topic": "/Arts & Entertainment/TV Shows & Programs/TV Sci-Fi & Fantasy Shows  "},
        { "ID": 53  ,  "Topic": "/Arts & Entertainment/Visual Art & Design"},
        { "ID": 54  ,  "Topic": "/Arts & Entertainment/Visual Art & Design/Design "},
        { "ID": 55  ,  "Topic": "/Arts & Entertainment/Visual Art & Design/Painting"},
        { "ID": 56  ,  "Topic": "/Arts & Entertainment/Visual Art & Design/Photographic & Digital Arts"},
        { "ID": 57  ,  "Topic": "/Autos & Vehicles"},
        { "ID": 58  ,  "Topic": "/Autos & Vehicles/Cargo Trucks & Trailers"},
        { "ID": 59  ,  "Topic": "/Autos & Vehicles/Classic Vehicles"},
        { "ID": 60  ,  "Topic": "/Autos & Vehicles/Custom & Performance Vehicles  "},
        { "ID": 61  ,  "Topic": "/Autos & Vehicles/Gas Prices & Vehicle Fueling"},
        { "ID": 62  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)"},
        { "ID": 63  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Autonomous Vehicles"},
        { "ID": 64  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Convertibles  "},
        { "ID": 65  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Coupes"},
        { "ID": 66  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Hatchbacks"},
        { "ID": 67  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles "},
        { "ID": 68  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Luxury Vehicles"},
        { "ID": 69  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Microcars & Subcompacts"},
        { "ID": 70  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles"},
        { "ID": 71  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Off-Road Vehicles "},
        { "ID": 72  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Pickup Trucks "},
        { "ID": 73  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Scooters & Mopeds "},
        { "ID": 74  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Sedans"},
        { "ID": 75  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Station Wagons"},
        { "ID": 76  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/SUVs & Crossovers "},
        { "ID": 77  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/SUVs & Crossovers/Crossovers  "},
        { "ID": 78  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Vans & Minivans"},
        { "ID": 79  ,  "Topic": "/Autos & Vehicles/Towing & Roadside Assistance"},
        { "ID": 80  ,  "Topic": "/Autos & Vehicles/Vehicle & Traffic Safety"},
        { "ID": 81  ,  "Topic": "/Autos & Vehicles/Vehicle Parts & Accessories"},
        { "ID": 82  ,  "Topic": "/Autos & Vehicles/Vehicle Repair & Maintenance"},
        { "ID": 83  ,  "Topic": "/Autos & Vehicles/Vehicle Shopping"},
        { "ID": 84  ,  "Topic": "/Autos & Vehicles/Vehicle Shopping/Used Vehicles "},
        { "ID": 85  ,  "Topic": "/Autos & Vehicles/Vehicle Shows  "},
        { "ID": 86  ,  "Topic": "/Beauty & Fitness"},
        { "ID": 87  ,  "Topic": "/Beauty & Fitness/Body Art"},
        { "ID": 88  ,  "Topic": "/Beauty & Fitness/Face & Body Care"},
        { "ID": 89  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Antiperspirants, Deodorants & Body Sprays "},
        { "ID": 90  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Bath & Body Products  "},
        { "ID": 91  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Clean Beauty  "},
        { "ID": 92  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics"},
        { "ID": 93  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Nail Care Products"},
        { "ID": 94  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Perfumes & Fragrances "},
        { "ID": 95  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Razors & Shavers  "},
        { "ID": 96  ,  "Topic": "/Beauty & Fitness/Fashion & Style"},
        { "ID": 97  ,  "Topic": "/Beauty & Fitness/Fitness"},
        { "ID": 98  ,  "Topic": "/Beauty & Fitness/Fitness/Bodybuilding"},
        { "ID": 99  ,  "Topic": "/Beauty & Fitness/Hair Care  "},
        { "ID": 100 ,  "Topic": "/Books & Literature  "},
        { "ID": 101 ,  "Topic": "/Books & Literature/Children's Literature"},
        { "ID": 102 ,  "Topic": "/Books & Literature/Poetry"},
        { "ID": 103 ,  "Topic": "/Business & Industrial"},
        { "ID": 104 ,  "Topic": "/Business & Industrial/Advertising & Marketing"},
        { "ID": 105 ,  "Topic": "/Business & Industrial/Advertising & Marketing/Sales "},
        { "ID": 106 ,  "Topic": "/Business & Industrial/Agriculture & Forestry"},
        { "ID": 107 ,  "Topic": "/Business & Industrial/Agriculture & Forestry/Food Production"},
        { "ID": 108 ,  "Topic": "/Business & Industrial/Automotive Industry"},
        { "ID": 109 ,  "Topic": "/Business & Industrial/Aviation Industry "},
        { "ID": 110 ,  "Topic": "/Business & Industrial/Business Operations"},
        { "ID": 111 ,  "Topic": "/Business & Industrial/Business Operations/Flexible Work Arrangements"},
        { "ID": 112 ,  "Topic": "/Business & Industrial/Business Operations/Human Resources"},
        { "ID": 113 ,  "Topic": "/Business & Industrial/Commercial Lending"},
        { "ID": 114 ,  "Topic": "/Business & Industrial/Construction & Maintenance"},
        { "ID": 115 ,  "Topic": "/Business & Industrial/Construction & Maintenance/Civil Engineering  "},
        { "ID": 116 ,  "Topic": "/Business & Industrial/Defense Industry  "},
        { "ID": 117 ,  "Topic": "/Business & Industrial/Energy & Utilities"},
        { "ID": 118 ,  "Topic": "/Business & Industrial/Energy & Utilities/Water Supply & Treatment"},
        { "ID": 119 ,  "Topic": "/Business & Industrial/Hospitality Industry  "},
        { "ID": 120 ,  "Topic": "/Business & Industrial/Manufacturing "},
        { "ID": 121 ,  "Topic": "/Business & Industrial/Metals & Mining"},
        { "ID": 122 ,  "Topic": "/Business & Industrial/Pharmaceuticals & Biotech "},
        { "ID": 123 ,  "Topic": "/Business & Industrial/Printing & Publishing "},
        { "ID": 124 ,  "Topic": "/Business & Industrial/Retail Trade  "},
        { "ID": 125 ,  "Topic": "/Business & Industrial/Venture Capital"},
        { "ID": 126 ,  "Topic": "/Computers & Electronics "},
        { "ID": 127 ,  "Topic": "/Computers & Electronics/Antivirus & Malware "},
        { "ID": 128 ,  "Topic": "/Computers & Electronics/Computer Peripherals"},
        { "ID": 129 ,  "Topic": "/Computers & Electronics/Consumer Electronics"},
        { "ID": 130 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Cameras & Camcorders"},
        { "ID": 131 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Home Automation"},
        { "ID": 132 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Home Theater Systems"},
        { "ID": 133 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Wearable Technology"},
        { "ID": 134 ,  "Topic": "/Computers & Electronics/Desktop Computers"},
        { "ID": 135 ,  "Topic": "/Computers & Electronics/Laptops & Notebooks "},
        { "ID": 136 ,  "Topic": "/Computers & Electronics/Network Security"},
        { "ID": 137 ,  "Topic": "/Computers & Electronics/Networking  "},
        { "ID": 138 ,  "Topic": "/Computers & Electronics/Networking/Distributed & Cloud Computing"},
        { "ID": 139 ,  "Topic": "/Computers & Electronics/Programming "},
        { "ID": 140 ,  "Topic": "/Computers & Electronics/Software"},
        { "ID": 141 ,  "Topic": "/Computers & Electronics/Software/Audio & Music Software "},
        { "ID": 142 ,  "Topic": "/Computers & Electronics/Software/Desktop Publishing "},
        { "ID": 143 ,  "Topic": "/Computers & Electronics/Software/Freeware & Shareware"},
        { "ID": 144 ,  "Topic": "/Computers & Electronics/Software/Graphics & Animation Software  "},
        { "ID": 145 ,  "Topic": "/Computers & Electronics/Software/Operating Systems  "},
        { "ID": 146 ,  "Topic": "/Computers & Electronics/Software/Photo Software "},
        { "ID": 147 ,  "Topic": "/Computers & Electronics/Software/Video Software "},
        { "ID": 148 ,  "Topic": "/Computers & Electronics/Software/Web Browsers"},
        { "ID": 149 ,  "Topic": "/Finance "},
        { "ID": 150 ,  "Topic": "/Finance/Accounting & Auditing"},
        { "ID": 151 ,  "Topic": "/Finance/Accounting & Auditing/Tax Preparation & Planning"},
        { "ID": 152 ,  "Topic": "/Finance/Credit Cards"},
        { "ID": 153 ,  "Topic": "/Finance/Financial Planning & Management "},
        { "ID": 154 ,  "Topic": "/Finance/Financial Planning & Management/Retirement & Pension"},
        { "ID": 155 ,  "Topic": "/Finance/Grants, Scholarships & Financial Aid"},
        { "ID": 156 ,  "Topic": "/Finance/Grants, Scholarships & Financial Aid/Study Grants & Scholarships"},
        { "ID": 157 ,  "Topic": "/Finance/Home Financing  "},
        { "ID": 158 ,  "Topic": "/Finance/Insurance"},
        { "ID": 159 ,  "Topic": "/Finance/Insurance/Auto Insurance"},
        { "ID": 160 ,  "Topic": "/Finance/Insurance/Health Insurance  "},
        { "ID": 161 ,  "Topic": "/Finance/Insurance/Home Insurance"},
        { "ID": 162 ,  "Topic": "/Finance/Insurance/Life Insurance"},
        { "ID": 163 ,  "Topic": "/Finance/Insurance/Travel Insurance  "},
        { "ID": 164 ,  "Topic": "/Finance/Investing"},
        { "ID": 165 ,  "Topic": "/Finance/Investing/Commodities & Futures Trading "},
        { "ID": 166 ,  "Topic": "/Finance/Investing/Currencies & Foreign Exchange "},
        { "ID": 167 ,  "Topic": "/Finance/Investing/Hedge Funds"},
        { "ID": 168 ,  "Topic": "/Finance/Investing/Mutual Funds  "},
        { "ID": 169 ,  "Topic": "/Finance/Investing/Stocks & Bonds"},
        { "ID": 170 ,  "Topic": "/Finance/Personal Loans  "},
        { "ID": 171 ,  "Topic": "/Finance/Student Loans & College Financing"},
        { "ID": 172 ,  "Topic": "/Food & Drink"},
        { "ID": 173 ,  "Topic": "/Food & Drink/Cooking & Recipes  "},
        { "ID": 174 ,  "Topic": "/Food & Drink/Cooking & Recipes/BBQ & Grilling"},
        { "ID": 175 ,  "Topic": "/Food & Drink/Cooking & Recipes/Cuisines "},
        { "ID": 176 ,  "Topic": "/Food & Drink/Cooking & Recipes/Cuisines/Vegetarian Cuisine  "},
        { "ID": 177 ,  "Topic": "/Food & Drink/Cooking & Recipes/Cuisines/Vegetarian Cuisine/Vegan Cuisine"},
        { "ID": 178 ,  "Topic": "/Food & Drink/Cooking & Recipes/Healthy Eating"},
        { "ID": 179 ,  "Topic": "/Food & Drink/Food & Grocery Retailers"},
        { "ID": 180 ,  "Topic": "/Games"},
        { "ID": 181 ,  "Topic": "/Games/Billiards "},
        { "ID": 182 ,  "Topic": "/Games/Card Games"},
        { "ID": 183 ,  "Topic": "/Games/Computer & Video Games"},
        { "ID": 184 ,  "Topic": "/Games/Computer & Video Games/Action & Platform Games"},
        { "ID": 185 ,  "Topic": "/Games/Computer & Video Games/Adventure Games"},
        { "ID": 186 ,  "Topic": "/Games/Computer & Video Games/Casual Games"},
        { "ID": 187 ,  "Topic": "/Games/Computer & Video Games/Competitive Video Gaming"},
        { "ID": 188 ,  "Topic": "/Games/Computer & Video Games/Massively Multiplayer Games"},
        { "ID": 189 ,  "Topic": "/Games/Computer & Video Games/Music & Dance Games"},
        { "ID": 190 ,  "Topic": "/Games/Computer & Video Games/Simulation Games"},
        { "ID": 191 ,  "Topic": "/Games/Computer & Video Games/Sports Games"},
        { "ID": 192 ,  "Topic": "/Games/Computer & Video Games/Strategy Games "},
        { "ID": 193 ,  "Topic": "/Games/Drawing & Coloring"},
        { "ID": 194 ,  "Topic": "/Games/Roleplaying Games "},
        { "ID": 195 ,  "Topic": "/Games/Table Tennis  "},
        { "ID": 196 ,  "Topic": "/Hobbies & Leisure"},
        { "ID": 197 ,  "Topic": "/Hobbies & Leisure/Anniversaries "},
        { "ID": 198 ,  "Topic": "/Hobbies & Leisure/Birthdays & Name Days "},
        { "ID": 199 ,  "Topic": "/Hobbies & Leisure/Diving & Underwater Activities"},
        { "ID": 200 ,  "Topic": "/Hobbies & Leisure/Fiber & Textile Arts  "},
        { "ID": 201 ,  "Topic": "/Hobbies & Leisure/Outdoors  "},
        { "ID": 202 ,  "Topic": "/Hobbies & Leisure/Outdoors/Fishing  "},
        { "ID": 203 ,  "Topic": "/Hobbies & Leisure/Outdoors/Hunting & Shooting"},
        { "ID": 204 ,  "Topic": "/Hobbies & Leisure/Paintball "},
        { "ID": 205 ,  "Topic": "/Hobbies & Leisure/Radio Control & Modeling  "},
        { "ID": 206 ,  "Topic": "/Hobbies & Leisure/Weddings  "},
        { "ID": 207 ,  "Topic": "/Home & Garden"},
        { "ID": 208 ,  "Topic": "/Home & Garden/Gardening "},
        { "ID": 209 ,  "Topic": "/Home & Garden/Home & Interior Decor "},
        { "ID": 210 ,  "Topic": "/Home & Garden/Home Appliances"},
        { "ID": 211 ,  "Topic": "/Home & Garden/Home Improvement  "},
        { "ID": 212 ,  "Topic": "/Home & Garden/Home Safety & Security"},
        { "ID": 213 ,  "Topic": "/Home & Garden/Household Supplies"},
        { "ID": 214 ,  "Topic": "/Home & Garden/Landscape Design  "},
        { "ID": 215 ,  "Topic": "/Internet & Telecom  "},
        { "ID": 216 ,  "Topic": "/Internet & Telecom/Email"},
        { "ID": 217 ,  "Topic": "/Internet & Telecom/ISPs "},
        { "ID": 218 ,  "Topic": "/Internet & Telecom/Phone Service Providers  "},
        { "ID": 219 ,  "Topic": "/Internet & Telecom/Search Engines"},
        { "ID": 220 ,  "Topic": "/Internet & Telecom/Smart Phones "},
        { "ID": 221 ,  "Topic": "/Internet & Telecom/Teleconferencing "},
        { "ID": 222 ,  "Topic": "/Internet & Telecom/Text & Instant Messaging "},
        { "ID": 223 ,  "Topic": "/Internet & Telecom/Web Apps & Online Tools  "},
        { "ID": 224 ,  "Topic": "/Internet & Telecom/Web Design & Development "},
        { "ID": 225 ,  "Topic": "/Internet & Telecom/Web Hosting  "},
        { "ID": 226 ,  "Topic": "/Jobs & Education"},
        { "ID": 227 ,  "Topic": "/Jobs & Education/Education  "},
        { "ID": 228 ,  "Topic": "/Jobs & Education/Education/Academic Conferences & Publications  "},
        { "ID": 229 ,  "Topic": "/Jobs & Education/Education/Colleges & Universities  "},
        { "ID": 230 ,  "Topic": "/Jobs & Education/Education/Distance Learning"},
        { "ID": 231 ,  "Topic": "/Jobs & Education/Education/Early Childhood Education"},
        { "ID": 232 ,  "Topic": "/Jobs & Education/Education/Early Childhood Education/Preschool  "},
        { "ID": 233 ,  "Topic": "/Jobs & Education/Education/Homeschooling"},
        { "ID": 234 ,  "Topic": "/Jobs & Education/Education/Standardized & Admissions Tests  "},
        { "ID": 235 ,  "Topic": "/Jobs & Education/Education/Vocational & Continuing Education"},
        { "ID": 236 ,  "Topic": "/Jobs & Education/Jobs"},
        { "ID": 237 ,  "Topic": "/Jobs & Education/Jobs/Career Resources & Planning"},
        { "ID": 238 ,  "Topic": "/Jobs & Education/Jobs/Job Listings  "},
        { "ID": 239 ,  "Topic": "/Law & Government"},
        { "ID": 240 ,  "Topic": "/Law & Government/Crime & Justice"},
        { "ID": 241 ,  "Topic": "/Law & Government/Legal  "},
        { "ID": 242 ,  "Topic": "/Law & Government/Legal/Legal Services"},
        { "ID": 243 ,  "Topic": "/News"},
        { "ID": 244 ,  "Topic": "/News/Economy News"},
        { "ID": 245 ,  "Topic": "/News/Local News "},
        { "ID": 246 ,  "Topic": "/News/Mergers & Acquisitions "},
        { "ID": 247 ,  "Topic": "/News/Politics"},
        { "ID": 248 ,  "Topic": "/News/Weather"},
        { "ID": 249 ,  "Topic": "/News/World News "},
        { "ID": 250 ,  "Topic": "/Online Communities  "},
        { "ID": 251 ,  "Topic": "/Online Communities/Dating & Personals"},
        { "ID": 252 ,  "Topic": "/Online Communities/Forum & Chat Providers"},
        { "ID": 253 ,  "Topic": "/Online Communities/Social Networks  "},
        { "ID": 254 ,  "Topic": "/People & Society"},
        { "ID": 255 ,  "Topic": "/People & Society/Family & Relationships "},
        { "ID": 256 ,  "Topic": "/People & Society/Family & Relationships/Ancestry & Genealogy"},
        { "ID": 257 ,  "Topic": "/People & Society/Family & Relationships/Marriage"},
        { "ID": 258 ,  "Topic": "/People & Society/Family & Relationships/Parenting"},
        { "ID": 259 ,  "Topic": "/People & Society/Family & Relationships/Parenting/Adoption  "},
        { "ID": 260 ,  "Topic": "/People & Society/Family & Relationships/Parenting/Babies & Toddlers "},
        { "ID": 261 ,  "Topic": "/People & Society/Family & Relationships/Parenting/Child Internet Safety "},
        { "ID": 262 ,  "Topic": "/People & Society/Science Fiction & Fantasy  "},
        { "ID": 263 ,  "Topic": "/Pets & Animals  "},
        { "ID": 264 ,  "Topic": "/Pets & Animals/Pet Food & Pet Care Supplies "},
        { "ID": 265 ,  "Topic": "/Pets & Animals/Pets "},
        { "ID": 266 ,  "Topic": "/Pets & Animals/Pets/Birds"},
        { "ID": 267 ,  "Topic": "/Pets & Animals/Pets/Cats"},
        { "ID": 268 ,  "Topic": "/Pets & Animals/Pets/Dogs"},
        { "ID": 269 ,  "Topic": "/Pets & Animals/Pets/Fish & Aquaria  "},
        { "ID": 270 ,  "Topic": "/Pets & Animals/Pets/Reptiles & Amphibians"},
        { "ID": 271 ,  "Topic": "/Pets & Animals/Veterinarians"},
        { "ID": 272 ,  "Topic": "/Real Estate "},
        { "ID": 273 ,  "Topic": "/Real Estate/Lots & Land "},
        { "ID": 274 ,  "Topic": "/Real Estate/Timeshares & Vacation Properties"},
        { "ID": 275 ,  "Topic": "/Reference"},
        { "ID": 276 ,  "Topic": "/Reference/Educational Resources "},
        { "ID": 277 ,  "Topic": "/Reference/Foreign Language Study"},
        { "ID": 278 ,  "Topic": "/Reference/How-To, DIY & Expert Content  "},
        { "ID": 279 ,  "Topic": "/Science "},
        { "ID": 280 ,  "Topic": "/Science/Augmented & Virtual Reality "},
        { "ID": 281 ,  "Topic": "/Science/Biological Sciences "},
        { "ID": 282 ,  "Topic": "/Science/Biological Sciences/Genetics"},
        { "ID": 283 ,  "Topic": "/Science/Chemistry"},
        { "ID": 284 ,  "Topic": "/Science/Ecology & Environment"},
        { "ID": 285 ,  "Topic": "/Science/Geology "},
        { "ID": 286 ,  "Topic": "/Science/Machine Learning & Artificial Intelligence  "},
        { "ID": 287 ,  "Topic": "/Science/Physics "},
        { "ID": 288 ,  "Topic": "/Science/Robotics"},
        { "ID": 289 ,  "Topic": "/Shopping"},
        { "ID": 290 ,  "Topic": "/Shopping/Antiques & Collectibles"},
        { "ID": 291 ,  "Topic": "/Shopping/Children's Clothing"},
        { "ID": 292 ,  "Topic": "/Shopping/Consumer Resources "},
        { "ID": 293 ,  "Topic": "/Shopping/Consumer Resources/Coupons & Discount Offers"},
        { "ID": 294 ,  "Topic": "/Shopping/Costumes"},
        { "ID": 295 ,  "Topic": "/Shopping/Flowers"},
        { "ID": 296 ,  "Topic": "/Shopping/Men's Clothing "},
        { "ID": 297 ,  "Topic": "/Shopping/Party & Holiday Supplies"},
        { "ID": 298 ,  "Topic": "/Shopping/Women's Clothing"},
        { "ID": 299 ,  "Topic": "/Sports  "},
        { "ID": 300 ,  "Topic": "/Sports/American Football"},
        { "ID": 301 ,  "Topic": "/Sports/Australian Football  "},
        { "ID": 302 ,  "Topic": "/Sports/Auto Racing  "},
        { "ID": 303 ,  "Topic": "/Sports/Baseball "},
        { "ID": 304 ,  "Topic": "/Sports/Basketball"},
        { "ID": 305 ,  "Topic": "/Sports/Bowling  "},
        { "ID": 306 ,  "Topic": "/Sports/Boxing"},
        { "ID": 307 ,  "Topic": "/Sports/Cheerleading "},
        { "ID": 308 ,  "Topic": "/Sports/College Sports"},
        { "ID": 309 ,  "Topic": "/Sports/Cricket  "},
        { "ID": 310 ,  "Topic": "/Sports/Cycling  "},
        { "ID": 311 ,  "Topic": "/Sports/Equestrian"},
        { "ID": 312 ,  "Topic": "/Sports/Extreme Sports"},
        { "ID": 313 ,  "Topic": "/Sports/Extreme Sports/Climbing & Mountaineering "},
        { "ID": 314 ,  "Topic": "/Sports/Fantasy Sports"},
        { "ID": 315 ,  "Topic": "/Sports/Golf "},
        { "ID": 316 ,  "Topic": "/Sports/Gymnastics"},
        { "ID": 317 ,  "Topic": "/Sports/Hockey"},
        { "ID": 318 ,  "Topic": "/Sports/Ice Skating  "},
        { "ID": 319 ,  "Topic": "/Sports/Martial Arts "},
        { "ID": 320 ,  "Topic": "/Sports/Motorcycle Racing"},
        { "ID": 321 ,  "Topic": "/Sports/Olympics "},
        { "ID": 322 ,  "Topic": "/Sports/Rugby"},
        { "ID": 323 ,  "Topic": "/Sports/Running & Walking"},
        { "ID": 324 ,  "Topic": "/Sports/Skiing & Snowboarding"},
        { "ID": 325 ,  "Topic": "/Sports/Soccer"},
        { "ID": 326 ,  "Topic": "/Sports/Surfing  "},
        { "ID": 327 ,  "Topic": "/Sports/Swimming "},
        { "ID": 328 ,  "Topic": "/Sports/Tennis"},
        { "ID": 329 ,  "Topic": "/Sports/Track & Field"},
        { "ID": 330 ,  "Topic": "/Sports/Volleyball"},
        { "ID": 331 ,  "Topic": "/Sports/Wrestling"},
        { "ID": 332 ,  "Topic": "/Travel & Transportation "},
        { "ID": 333 ,  "Topic": "/Travel & Transportation/Adventure Travel"},
        { "ID": 334 ,  "Topic": "/Travel & Transportation/Air Travel  "},
        { "ID": 335 ,  "Topic": "/Travel & Transportation/Business Travel "},
        { "ID": 336 ,  "Topic": "/Travel & Transportation/Car Rentals "},
        { "ID": 337 ,  "Topic": "/Travel & Transportation/Cruises & Charters  "},
        { "ID": 338 ,  "Topic": "/Travel & Transportation/Family Travel"},
        { "ID": 339 ,  "Topic": "/Travel & Transportation/Honeymoons & Romantic Getaways  "},
        { "ID": 340 ,  "Topic": "/Travel & Transportation/Hotels & Accommodations "},
        { "ID": 341 ,  "Topic": "/Travel & Transportation/Long Distance Bus & Rail"},
        { "ID": 342 ,  "Topic": "/Travel & Transportation/Low Cost & Last Minute Travel"},
        { "ID": 343 ,  "Topic": "/Travel & Transportation/Luggage & Travel Accessories"},
        { "ID": 344 ,  "Topic": "/Travel & Transportation/Tourist Destinations"},
        { "ID": 345 ,  "Topic": "/Travel & Transportation/Tourist Destinations/Beaches & Islands  "},
        { "ID": 346 ,  "Topic": "/Travel & Transportation/Tourist Destinations/Regional Parks & Gardens"},
        { "ID": 347 ,  "Topic": "/Travel & Transportation/Tourist Destinations/Theme Parks"},
        { "ID": 348 ,  "Topic": "/Travel & Transportation/Tourist Destinations/Zoos, Aquariums & Preserves"},
        { "ID": 349 ,  "Topic": "/Travel & Transportation/Travel Guides & Travelogues "},
        { "ID": 1,  "Topic": "/Arts & Entertainment"},
        { "ID": 350 ,  "Topic": "/Arts & Entertainment/Celebrities & Entertainment News"},
        { "ID": 351 ,  "Topic": "/Arts & Entertainment/Comics & Animation "},
        { "ID": 352 ,  "Topic": "/Arts & Entertainment/Events & Listings  "},
        { "ID": 353 ,  "Topic": "/Arts & Entertainment/Events & Listings/Bars, Clubs & Nightlife  "},
        { "ID": 4,  "Topic": "/Arts & Entertainment/Events & Listings/Concerts & Music Festivals"},
        { "ID": 354 ,  "Topic": "/Arts & Entertainment/Events & Listings/Event Ticket Sales"},
        { "ID": 355 ,  "Topic": "/Arts & Entertainment/Events & Listings/Expos & Conventions  "},
        { "ID": 356 ,  "Topic": "/Arts & Entertainment/Events & Listings/Film Festivals"},
        { "ID": 357 ,  "Topic": "/Arts & Entertainment/Events & Listings/Food & Beverage Events"},
        { "ID": 9,  "Topic": "/Arts & Entertainment/Events & Listings/Live Sporting Events "},
        { "ID": 12  ,  "Topic": "/Arts & Entertainment/Movies "},
        { "ID": 13  ,  "Topic": "/Arts & Entertainment/Movies/Action & Adventure Films"},
        { "ID": 15  ,  "Topic": "/Arts & Entertainment/Movies/Comedy Films"},
        { "ID": 18  ,  "Topic": "/Arts & Entertainment/Movies/Drama Films "},
        { "ID": 19  ,  "Topic": "/Arts & Entertainment/Movies/Family Films"},
        { "ID": 20  ,  "Topic": "/Arts & Entertainment/Movies/Horror Films"},
        { "ID": 21  ,  "Topic": "/Arts & Entertainment/Movies/Romance Films"},
        { "ID": 358 ,  "Topic": "/Arts & Entertainment/Movies/Science Fiction & Fantasy Films "},
        { "ID": 23  ,  "Topic": "/Arts & Entertainment/Music & Audio  "},
        { "ID": 24  ,  "Topic": "/Arts & Entertainment/Music & Audio/Blues"},
        { "ID": 25  ,  "Topic": "/Arts & Entertainment/Music & Audio/Classical Music  "},
        { "ID": 26  ,  "Topic": "/Arts & Entertainment/Music & Audio/Country Music"},
        { "ID": 27  ,  "Topic": "/Arts & Entertainment/Music & Audio/Dance & Electronic Music "},
        { "ID": 359 ,  "Topic": "/Arts & Entertainment/Music & Audio/DJ Resources & Equipment "},
        { "ID": 28  ,  "Topic": "/Arts & Entertainment/Music & Audio/Folk & Traditional Music "},
        { "ID": 29  ,  "Topic": "/Arts & Entertainment/Music & Audio/Jazz "},
        { "ID": 30  ,  "Topic": "/Arts & Entertainment/Music & Audio/Musical Instruments  "},
        { "ID": 31  ,  "Topic": "/Arts & Entertainment/Music & Audio/Pop Music"},
        { "ID": 32  ,  "Topic": "/Arts & Entertainment/Music & Audio/Rap & Hip-Hop"},
        { "ID": 33  ,  "Topic": "/Arts & Entertainment/Music & Audio/Rock Music"},
        { "ID": 36  ,  "Topic": "/Arts & Entertainment/Music & Audio/Rock Music/Indie & Alternative Music "},
        { "ID": 360 ,  "Topic": "/Arts & Entertainment/Music & Audio/Rock Music/Metal (Music) "},
        { "ID": 361 ,  "Topic": "/Arts & Entertainment/Performing Arts"},
        { "ID": 362 ,  "Topic": "/Arts & Entertainment/Performing Arts/Broadway & Musical Theater "},
        { "ID": 363 ,  "Topic": "/Arts & Entertainment/TV & Video "},
        { "ID": 364 ,  "Topic": "/Arts & Entertainment/TV & Video/Live Video Streaming"},
        { "ID": 365 ,  "Topic": "/Arts & Entertainment/TV & Video/Movie & TV Streaming"},
        { "ID": 46  ,  "Topic": "/Arts & Entertainment/TV & Video/TV Comedies "},
        { "ID": 47  ,  "Topic": "/Arts & Entertainment/TV & Video/TV Documentary & Nonfiction "},
        { "ID": 48  ,  "Topic": "/Arts & Entertainment/TV & Video/TV Dramas"},
        { "ID": 50  ,  "Topic": "/Arts & Entertainment/TV & Video/TV Family-Oriented Shows"},
        { "ID": 366 ,  "Topic": "/Arts & Entertainment/TV & Video/TV Game Shows"},
        { "ID": 51  ,  "Topic": "/Arts & Entertainment/TV & Video/TV Reality Shows"},
        { "ID": 52  ,  "Topic": "/Arts & Entertainment/TV & Video/TV Sci-Fi & Fantasy Shows"},
        { "ID": 367 ,  "Topic": "/Arts & Entertainment/TV & Video/TV Talk Shows"},
        { "ID": 53  ,  "Topic": "/Arts & Entertainment/Visual Art & Design"},
        { "ID": 368 ,  "Topic": "/Arts & Entertainment/Visual Art & Design/Architecture"},
        { "ID": 56  ,  "Topic": "/Arts & Entertainment/Visual Art & Design/Photographic & Digital Arts"},
        { "ID": 57  ,  "Topic": "/Autos & Vehicles"},
        { "ID": 369 ,  "Topic": "/Autos & Vehicles/Bicycles & Accessories "},
        { "ID": 370 ,  "Topic": "/Autos & Vehicles/Boats & Watercraft "},
        { "ID": 371 ,  "Topic": "/Autos & Vehicles/Campers & RVs  "},
        { "ID": 59  ,  "Topic": "/Autos & Vehicles/Classic Vehicles"},
        { "ID": 372 ,  "Topic": "/Autos & Vehicles/Commercial Vehicles"},
        { "ID": 60  ,  "Topic": "/Autos & Vehicles/Custom & Performance Vehicles  "},
        { "ID": 62  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)"},
        { "ID": 63  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Autonomous Vehicles"},
        { "ID": 373 ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Compact Cars  "},
        { "ID": 64  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Convertibles  "},
        { "ID": 65  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Coupes"},
        { "ID": 374 ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Diesel Vehicles"},
        { "ID": 66  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Hatchbacks"},
        { "ID": 67  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles "},
        { "ID": 375 ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Hybrid & Alternative Vehicles/Electric & Plug-In Vehicles "},
        { "ID": 68  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Luxury Vehicles"},
        { "ID": 69  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Microcars & Subcompacts"},
        { "ID": 70  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Motorcycles"},
        { "ID": 71  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Off-Road Vehicles "},
        { "ID": 73  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Scooters & Mopeds "},
        { "ID": 74  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Sedans"},
        { "ID": 376 ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Sports Cars"},
        { "ID": 75  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Station Wagons"},
        { "ID": 377 ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Trucks, Vans & SUVs"},
        { "ID": 72  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Trucks, Vans & SUVs/Pickup Trucks "},
        { "ID": 76  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Trucks, Vans & SUVs/SUVs & Crossovers "},
        { "ID": 78  ,  "Topic": "/Autos & Vehicles/Motor Vehicles (By Type)/Trucks, Vans & SUVs/Vans & Minivans"},
        { "ID": 81  ,  "Topic": "/Autos & Vehicles/Vehicle Parts & Accessories"},
        { "ID": 378 ,  "Topic": "/Autos & Vehicles/Vehicle Parts & Accessories/High Performance & Aftermarket Auto Parts  "},
        { "ID": 379 ,  "Topic": "/Autos & Vehicles/Vehicle Parts & Accessories/Vehicle Wheels & Tires "},
        { "ID": 82  ,  "Topic": "/Autos & Vehicles/Vehicle Repair & Maintenance"},
        { "ID": 83  ,  "Topic": "/Autos & Vehicles/Vehicle Shopping"},
        { "ID": 84  ,  "Topic": "/Autos & Vehicles/Vehicle Shopping/Used Vehicles "},
        { "ID": 86  ,  "Topic": "/Beauty & Fitness"},
        { "ID": 380 ,  "Topic": "/Beauty & Fitness/Beauty Services & Spas "},
        { "ID": 381 ,  "Topic": "/Beauty & Fitness/Beauty Services & Spas/Manicures & Pedicures"},
        { "ID": 382 ,  "Topic": "/Beauty & Fitness/Cosmetology & Beauty Professionals "},
        { "ID": 88  ,  "Topic": "/Beauty & Fitness/Face & Body Care"},
        { "ID": 91  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Clean Beauty  "},
        { "ID": 383 ,  "Topic": "/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries  "},
        { "ID": 89  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries/Antiperspirants, Deodorants & Body Sprays"},
        { "ID": 384 ,  "Topic": "/Beauty & Fitness/Face & Body Care/Hygiene & Toiletries/Feminine Hygiene Products"},
        { "ID": 92  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Make-Up & Cosmetics"},
        { "ID": 94  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Perfumes & Fragrances "},
        { "ID": 385 ,  "Topic": "/Beauty & Fitness/Face & Body Care/Skin & Nail Care  "},
        { "ID": 90  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Skin & Nail Care/Bath & Body Products "},
        { "ID": 386 ,  "Topic": "/Beauty & Fitness/Face & Body Care/Skin & Nail Care/Face Care Products"},
        { "ID": 93  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Skin & Nail Care/Nail Care Products"},
        { "ID": 387 ,  "Topic": "/Beauty & Fitness/Face & Body Care/Sun Care & Tanning Products"},
        { "ID": 388 ,  "Topic": "/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal"},
        { "ID": 95  ,  "Topic": "/Beauty & Fitness/Face & Body Care/Unwanted Body & Facial Hair Removal/Razors & Shavers  "},
        { "ID": 96  ,  "Topic": "/Beauty & Fitness/Fashion & Style"},
        { "ID": 97  ,  "Topic": "/Beauty & Fitness/Fitness"},
        { "ID": 389 ,  "Topic": "/Beauty & Fitness/Fitness/Fitness Equipment & Accessories"},
        { "ID": 390 ,  "Topic": "/Beauty & Fitness/Fitness/Fitness Equipment & Accessories/Fitness Technology Products"},
        { "ID": 391 ,  "Topic": "/Beauty & Fitness/Fitness/Fitness Instruction & Personal Training"},
        { "ID": 392 ,  "Topic": "/Beauty & Fitness/Fitness/Gyms & Health Clubs"},
        { "ID": 393 ,  "Topic": "/Beauty & Fitness/Fitness/High Intensity Interval Training"},
        { "ID": 394 ,  "Topic": "/Beauty & Fitness/Fitness/Yoga & Pilates "},
        { "ID": 99  ,  "Topic": "/Beauty & Fitness/Hair Care  "},
        { "ID": 395 ,  "Topic": "/Beauty & Fitness/Hair Care/Shampoos & Conditioners  "},
        { "ID": 100 ,  "Topic": "/Books & Literature  "},
        { "ID": 396 ,  "Topic": "/Books & Literature/Audiobooks"},
        { "ID": 397 ,  "Topic": "/Books & Literature/Book Retailers"},
        { "ID": 101 ,  "Topic": "/Books & Literature/Children's Literature"},
        { "ID": 398 ,  "Topic": "/Books & Literature/Fan Fiction  "},
        { "ID": 399 ,  "Topic": "/Books & Literature/Literary Classics"},
        { "ID": 400 ,  "Topic": "/Books & Literature/Magazines"},
        { "ID": 102 ,  "Topic": "/Books & Literature/Poetry"},
        { "ID": 401 ,  "Topic": "/Books & Literature/Writers Resources"},
        { "ID": 103 ,  "Topic": "/Business & Industrial"},
        { "ID": 104 ,  "Topic": "/Business & Industrial/Advertising & Marketing"},
        { "ID": 402 ,  "Topic": "/Business & Industrial/Building Materials & Supplies "},
        { "ID": 403 ,  "Topic": "/Business & Industrial/Business Finance  "},
        { "ID": 113 ,  "Topic": "/Business & Industrial/Business Finance/Commercial Lending"},
        { "ID": 404 ,  "Topic": "/Business & Industrial/Business Services "},
        { "ID": 405 ,  "Topic": "/Business & Industrial/Business Services/Corporate Events"},
        { "ID": 406 ,  "Topic": "/Business & Industrial/Business Services/Fire & Security Services"},
        { "ID": 407 ,  "Topic": "/Business & Industrial/Business Services/Merchant Services & Payment Systems "},
        { "ID": 408 ,  "Topic": "/Business & Industrial/Business Services/Office Supplies "},
        { "ID": 409 ,  "Topic": "/Business & Industrial/Business Services/Office Supplies/Office Furniture"},
        { "ID": 410 ,  "Topic": "/Business & Industrial/Business Services/Signage "},
        { "ID": 411 ,  "Topic": "/Business & Industrial/Construction Consulting & Contracting "},
        { "ID": 412 ,  "Topic": "/Business & Industrial/Document & Printing Services  "},
        { "ID": 413 ,  "Topic": "/Business & Industrial/Event Planning"},
        { "ID": 414 ,  "Topic": "/Business & Industrial/Food Service  "},
        { "ID": 415 ,  "Topic": "/Business & Industrial/Industrial Materials & Equipment  "},
        { "ID": 416 ,  "Topic": "/Business & Industrial/Industrial Materials & Equipment/Work Safety Protective Gear  "},
        { "ID": 417 ,  "Topic": "/Business & Industrial/Moving & Relocation"},
        { "ID": 418 ,  "Topic": "/Business & Industrial/Payroll Services  "},
        { "ID": 419 ,  "Topic": "/Business & Industrial/Recruitment & Staffing"},
        { "ID": 126 ,  "Topic": "/Computers & Electronics "},
        { "ID": 420 ,  "Topic": "/Computers & Electronics/Computer Hardware"},
        { "ID": 421 ,  "Topic": "/Computers & Electronics/Computer Hardware/Computer Components"},
        { "ID": 422 ,  "Topic": "/Computers & Electronics/Computer Hardware/Computer Drives & Storage "},
        { "ID": 128 ,  "Topic": "/Computers & Electronics/Computer Hardware/Computer Peripherals  "},
        { "ID": 134 ,  "Topic": "/Computers & Electronics/Computer Hardware/Desktop Computers "},
        { "ID": 135 ,  "Topic": "/Computers & Electronics/Computer Hardware/Laptops & Notebooks"},
        { "ID": 423 ,  "Topic": "/Computers & Electronics/Computer Security"},
        { "ID": 129 ,  "Topic": "/Computers & Electronics/Consumer Electronics"},
        { "ID": 424 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Audio Equipment"},
        { "ID": 425 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Audio Equipment/Headphones "},
        { "ID": 426 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Audio Equipment/Speakers"},
        { "ID": 427 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Audio Equipment/Stereo Systems & Components"},
        { "ID": 428 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Camera & Photo Equipment"},
        { "ID": 429 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Car Audio  "},
        { "ID": 430 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Gadgets & Portable Electronics "},
        { "ID": 431 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Game Systems & Consoles"},
        { "ID": 432 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Game Systems & Consoles/Handheld Game Consoles "},
        { "ID": 131 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Home Automation"},
        { "ID": 132 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Home Theater Systems"},
        { "ID": 433 ,  "Topic": "/Computers & Electronics/Consumer Electronics/Televisions"},
        { "ID": 434 ,  "Topic": "/Computers & Electronics/Electronics & Electrical"},
        { "ID": 435 ,  "Topic": "/Computers & Electronics/Electronics & Electrical/Power Supplies "},
        { "ID": 436 ,  "Topic": "/Computers & Electronics/Enterprise Technology"},
        { "ID": 137 ,  "Topic": "/Computers & Electronics/Networking  "},
        { "ID": 437 ,  "Topic": "/Computers & Electronics/Networking/Network Monitoring & Management  "},
        { "ID": 438 ,  "Topic": "/Computers & Electronics/Networking/Networking Equipment "},
        { "ID": 140 ,  "Topic": "/Computers & Electronics/Software"},
        { "ID": 439 ,  "Topic": "/Computers & Electronics/Software/Business & Productivity Software"},
        { "ID": 440 ,  "Topic": "/Computers & Electronics/Software/Business & Productivity Software/Accounting & Financial Software"},
        { "ID": 441 ,  "Topic": "/Computers & Electronics/Software/Business & Productivity Software/Collaboration & Conferencing Software "},
        { "ID": 442 ,  "Topic": "/Computers & Electronics/Software/Multimedia Software"},
        { "ID": 141 ,  "Topic": "/Computers & Electronics/Software/Multimedia Software/Audio & Music Software "},
        { "ID": 144 ,  "Topic": "/Computers & Electronics/Software/Multimedia Software/Graphics & Animation Software  "},
        { "ID": 443 ,  "Topic": "/Computers & Electronics/Software/Multimedia Software/Photo & Video Software "},
        { "ID": 149 ,  "Topic": "/Finance "},
        { "ID": 150 ,  "Topic": "/Finance/Accounting & Auditing"},
        { "ID": 151 ,  "Topic": "/Finance/Accounting & Auditing/Tax Preparation & Planning"},
        { "ID": 444 ,  "Topic": "/Finance/Banking "},
        { "ID": 445 ,  "Topic": "/Finance/Banking/Debit & Checking Services"},
        { "ID": 446 ,  "Topic": "/Finance/Banking/Savings Accounts"},
        { "ID": 447 ,  "Topic": "/Finance/Credit & Lending"},
        { "ID": 448 ,  "Topic": "/Finance/Credit & Lending/Auto Financing "},
        { "ID": 152 ,  "Topic": "/Finance/Credit & Lending/Credit Cards"},
        { "ID": 449 ,  "Topic": "/Finance/Credit & Lending/Credit Reporting & Monitoring  "},
        { "ID": 157 ,  "Topic": "/Finance/Credit & Lending/Home Financing "},
        { "ID": 170 ,  "Topic": "/Finance/Credit & Lending/Personal Loans "},
        { "ID": 171 ,  "Topic": "/Finance/Credit & Lending/Student Loans & College Financing  "},
        { "ID": 153 ,  "Topic": "/Finance/Financial Planning & Management "},
        { "ID": 154 ,  "Topic": "/Finance/Financial Planning & Management/Retirement & Pension"},
        { "ID": 158 ,  "Topic": "/Finance/Insurance"},
        { "ID": 159 ,  "Topic": "/Finance/Insurance/Auto Insurance"},
        { "ID": 160 ,  "Topic": "/Finance/Insurance/Health Insurance  "},
        { "ID": 161 ,  "Topic": "/Finance/Insurance/Home Insurance"},
        { "ID": 162 ,  "Topic": "/Finance/Insurance/Life Insurance"},
        { "ID": 163 ,  "Topic": "/Finance/Insurance/Travel Insurance  "},
        { "ID": 164 ,  "Topic": "/Finance/Investing"},
        { "ID": 172 ,  "Topic": "/Food & Drink"},
        { "ID": 173 ,  "Topic": "/Food & Drink/Cooking & Recipes  "},
        { "ID": 176 ,  "Topic": "/Food & Drink/Cooking & Recipes/Vegetarian Cuisine"},
        { "ID": 177 ,  "Topic": "/Food & Drink/Cooking & Recipes/Vegetarian Cuisine/Vegan Cuisine "},
        { "ID": 450 ,  "Topic": "/Food & Drink/Food"},
        { "ID": 451 ,  "Topic": "/Food & Drink/Food/Baked Goods"},
        { "ID": 452 ,  "Topic": "/Food & Drink/Food/Breakfast Foods"},
        { "ID": 453 ,  "Topic": "/Food & Drink/Food/Candy & Sweets"},
        { "ID": 454 ,  "Topic": "/Food & Drink/Food/Condiments & Dressings"},
        { "ID": 455 ,  "Topic": "/Food & Drink/Food/Dairy & Eggs  "},
        { "ID": 456 ,  "Topic": "/Food & Drink/Food/Gourmet & Specialty Foods "},
        { "ID": 457 ,  "Topic": "/Food & Drink/Food/Meat & Seafood"},
        { "ID": 458 ,  "Topic": "/Food & Drink/Food/Meat & Seafood/Fish & Seafood "},
        { "ID": 459 ,  "Topic": "/Food & Drink/Food/Organic & Natural Foods"},
        { "ID": 460 ,  "Topic": "/Food & Drink/Grocery Delivery Services  "},
        { "ID": 461 ,  "Topic": "/Food & Drink/Restaurant Delivery Services"},
        { "ID": 462 ,  "Topic": "/Food & Drink/Restaurants"},
        { "ID": 463 ,  "Topic": "/Food & Drink/Restaurants/Fast Food  "},
        { "ID": 464 ,  "Topic": "/Food & Drink/Restaurants/Pizzerias  "},
        { "ID": 180 ,  "Topic": "/Games"},
        { "ID": 465 ,  "Topic": "/Games/Board Games"},
        { "ID": 183 ,  "Topic": "/Games/Computer & Video Games"},
        { "ID": 184 ,  "Topic": "/Games/Computer & Video Games/Action & Platform Games"},
        { "ID": 185 ,  "Topic": "/Games/Computer & Video Games/Adventure Games"},
        { "ID": 186 ,  "Topic": "/Games/Computer & Video Games/Casual Games"},
        { "ID": 187 ,  "Topic": "/Games/Computer & Video Games/Competitive Video Gaming"},
        { "ID": 466 ,  "Topic": "/Games/Computer & Video Games/Driving & Racing Games "},
        { "ID": 467 ,  "Topic": "/Games/Computer & Video Games/Shooter Games  "},
        { "ID": 191 ,  "Topic": "/Games/Computer & Video Games/Sports Games"},
        { "ID": 192 ,  "Topic": "/Games/Computer & Video Games/Strategy Games "},
        { "ID": 468 ,  "Topic": "/Games/Family-Oriented Games & Activities"},
        { "ID": 194 ,  "Topic": "/Games/Roleplaying Games "},
        { "ID": 196 ,  "Topic": "/Hobbies & Leisure"},
        { "ID": 469 ,  "Topic": "/Hobbies & Leisure/Art & Craft Supplies  "},
        { "ID": 470 ,  "Topic": "/Hobbies & Leisure/Boating"},
        { "ID": 471 ,  "Topic": "/Hobbies & Leisure/Holidays & Seasonal Events"},
        { "ID": 201 ,  "Topic": "/Hobbies & Leisure/Outdoors  "},
        { "ID": 202 ,  "Topic": "/Hobbies & Leisure/Outdoors/Fishing  "},
        { "ID": 472 ,  "Topic": "/Hobbies & Leisure/Outdoors/Hiking & Camping "},
        { "ID": 207 ,  "Topic": "/Home & Garden"},
        { "ID": 473 ,  "Topic": "/Home & Garden/Bed & Bath"},
        { "ID": 474 ,  "Topic": "/Home & Garden/Bed & Bath/Bathroom"},
        { "ID": 475 ,  "Topic": "/Home & Garden/Bed & Bath/Bedroom"},
        { "ID": 476 ,  "Topic": "/Home & Garden/Bed & Bath/Bedroom/Bedding & Bed Linens"},
        { "ID": 477 ,  "Topic": "/Home & Garden/Bed & Bath/Bedroom/Beds & Headboards  "},
        { "ID": 478 ,  "Topic": "/Home & Garden/Bed & Bath/Bedroom/Mattresses "},
        { "ID": 479 ,  "Topic": "/Home & Garden/Cleaning Services "},
        { "ID": 209 ,  "Topic": "/Home & Garden/Home & Interior Decor "},
        { "ID": 210 ,  "Topic": "/Home & Garden/Home Appliances"},
        { "ID": 480 ,  "Topic": "/Home & Garden/Home Appliances/Vacuums & Floor Care  "},
        { "ID": 481 ,  "Topic": "/Home & Garden/Home Appliances/Water Filters & Purifiers "},
        { "ID": 482 ,  "Topic": "/Home & Garden/Home Furnishings  "},
        { "ID": 483 ,  "Topic": "/Home & Garden/Home Furnishings/Countertops  "},
        { "ID": 484 ,  "Topic": "/Home & Garden/Home Furnishings/Curtains & Window Treatments "},
        { "ID": 485 ,  "Topic": "/Home & Garden/Home Furnishings/Kitchen & Dining Furniture"},
        { "ID": 486 ,  "Topic": "/Home & Garden/Home Furnishings/Lamps & Lighting "},
        { "ID": 487 ,  "Topic": "/Home & Garden/Home Furnishings/Living Room Furniture"},
        { "ID": 488 ,  "Topic": "/Home & Garden/Home Furnishings/Living Room Furniture/Sofas & Armchairs  "},
        { "ID": 489 ,  "Topic": "/Home & Garden/Home Furnishings/Outdoor Furniture"},
        { "ID": 490 ,  "Topic": "/Home & Garden/Home Furnishings/Rugs & Carpets"},
        { "ID": 211 ,  "Topic": "/Home & Garden/Home Improvement  "},
        { "ID": 491 ,  "Topic": "/Home & Garden/Home Improvement/Construction & Power Tools"},
        { "ID": 492 ,  "Topic": "/Home & Garden/Home Improvement/Doors & Windows  "},
        { "ID": 493 ,  "Topic": "/Home & Garden/Home Improvement/Flooring "},
        { "ID": 494 ,  "Topic": "/Home & Garden/Home Improvement/House Painting & Finishing"},
        { "ID": 495 ,  "Topic": "/Home & Garden/Home Improvement/Locks & Locksmiths"},
        { "ID": 496 ,  "Topic": "/Home & Garden/Home Improvement/Plumbing "},
        { "ID": 497 ,  "Topic": "/Home & Garden/Home Improvement/Roofing  "},
        { "ID": 212 ,  "Topic": "/Home & Garden/Home Safety & Security"},
        { "ID": 498 ,  "Topic": "/Home & Garden/Home Storage & Shelving"},
        { "ID": 499 ,  "Topic": "/Home & Garden/Home Storage & Shelving/Cabinetry "},
        { "ID": 500 ,  "Topic": "/Home & Garden/Home Swimming Pools, Saunas & Spas"},
        { "ID": 213 ,  "Topic": "/Home & Garden/Household Supplies"},
        { "ID": 501 ,  "Topic": "/Home & Garden/Household Supplies/Household Batteries"},
        { "ID": 502 ,  "Topic": "/Home & Garden/Household Supplies/Household Cleaning Supplies"},
        { "ID": 503 ,  "Topic": "/Home & Garden/HVAC & Climate Control"},
        { "ID": 504 ,  "Topic": "/Home & Garden/HVAC & Climate Control/Air Conditioners"},
        { "ID": 505 ,  "Topic": "/Home & Garden/HVAC & Climate Control/Fireplaces & Stoves"},
        { "ID": 506 ,  "Topic": "/Home & Garden/HVAC & Climate Control/Household Fans "},
        { "ID": 507 ,  "Topic": "/Home & Garden/Kitchen & Dining  "},
        { "ID": 508 ,  "Topic": "/Home & Garden/Kitchen & Dining/Cookware & Diningware"},
        { "ID": 509 ,  "Topic": "/Home & Garden/Kitchen & Dining/Cookware & Diningware/Cookware"},
        { "ID": 510 ,  "Topic": "/Home & Garden/Kitchen & Dining/Cookware & Diningware/Diningware "},
        { "ID": 511 ,  "Topic": "/Home & Garden/Kitchen & Dining/Dishwashers  "},
        { "ID": 512 ,  "Topic": "/Home & Garden/Kitchen & Dining/Microwaves"},
        { "ID": 513 ,  "Topic": "/Home & Garden/Kitchen & Dining/Ranges, Cooktops & Ovens "},
        { "ID": 514 ,  "Topic": "/Home & Garden/Kitchen & Dining/Refrigerators & Freezers "},
        { "ID": 515 ,  "Topic": "/Home & Garden/Kitchen & Dining/Small Kitchen Appliances "},
        { "ID": 516 ,  "Topic": "/Home & Garden/Kitchen & Dining/Small Kitchen Appliances/Blenders & Juicers  "},
        { "ID": 517 ,  "Topic": "/Home & Garden/Kitchen & Dining/Small Kitchen Appliances/Coffee & Espresso Makers"},
        { "ID": 518 ,  "Topic": "/Home & Garden/Kitchen & Dining/Small Kitchen Appliances/Food Mixers "},
        { "ID": 519 ,  "Topic": "/Home & Garden/Patio, Lawn & Garden  "},
        { "ID": 520 ,  "Topic": "/Home & Garden/Patio, Lawn & Garden/Barbecues & Grills"},
        { "ID": 208 ,  "Topic": "/Home & Garden/Patio, Lawn & Garden/Gardening"},
        { "ID": 214 ,  "Topic": "/Home & Garden/Patio, Lawn & Garden/Landscape Design "},
        { "ID": 521 ,  "Topic": "/Home & Garden/Patio, Lawn & Garden/Yard Maintenance "},
        { "ID": 522 ,  "Topic": "/Home & Garden/Patio, Lawn & Garden/Yard Maintenance/Lawn Mowers "},
        { "ID": 523 ,  "Topic": "/Home & Garden/Pest Control  "},
        { "ID": 524 ,  "Topic": "/Home & Garden/Washers & Dryers  "},
        { "ID": 215 ,  "Topic": "/Internet & Telecom  "},
        { "ID": 525 ,  "Topic": "/Internet & Telecom/Communications Equipment "},
        { "ID": 526 ,  "Topic": "/Internet & Telecom/Communications Equipment/Radio Equipment "},
        { "ID": 527 ,  "Topic": "/Internet & Telecom/Mobile & Wireless Accessories"},
        { "ID": 528 ,  "Topic": "/Internet & Telecom/Mobile Phones"},
        { "ID": 529 ,  "Topic": "/Internet & Telecom/Mobile Phones/Mobile Phone Repair & Services "},
        { "ID": 530 ,  "Topic": "/Internet & Telecom/Service Providers"},
        { "ID": 531 ,  "Topic": "/Internet & Telecom/Service Providers/Cable & Satellite Providers"},
        { "ID": 217 ,  "Topic": "/Internet & Telecom/Service Providers/ISPs"},
        { "ID": 218 ,  "Topic": "/Internet & Telecom/Service Providers/Phone Service Providers"},
        { "ID": 532 ,  "Topic": "/Internet & Telecom/Voice & Video Chat"},
        { "ID": 533 ,  "Topic": "/Internet & Telecom/Web Services "},
        { "ID": 534 ,  "Topic": "/Internet & Telecom/Web Services/Cloud Storage"},
        { "ID": 535 ,  "Topic": "/Internet & Telecom/Web Services/Search Engine Optimization & Marketing  "},
        { "ID": 224 ,  "Topic": "/Internet & Telecom/Web Services/Web Design & Development"},
        { "ID": 536 ,  "Topic": "/Internet & Telecom/Web Services/Web Hosting & Domain Registration"},
        { "ID": 226 ,  "Topic": "/Jobs & Education"},
        { "ID": 227 ,  "Topic": "/Jobs & Education/Education  "},
        { "ID": 537 ,  "Topic": "/Jobs & Education/Education/Business Education"},
        { "ID": 229 ,  "Topic": "/Jobs & Education/Education/Colleges & Universities  "},
        { "ID": 538 ,  "Topic": "/Jobs & Education/Education/Computer Education"},
        { "ID": 230 ,  "Topic": "/Jobs & Education/Education/Distance Learning"},
        { "ID": 231 ,  "Topic": "/Jobs & Education/Education/Early Childhood Education"},
        { "ID": 277 ,  "Topic": "/Jobs & Education/Education/Foreign Language Study"},
        { "ID": 539 ,  "Topic": "/Jobs & Education/Education/Health Education & Medical Training  "},
        { "ID": 233 ,  "Topic": "/Jobs & Education/Education/Homeschooling"},
        { "ID": 540 ,  "Topic": "/Jobs & Education/Education/Legal Education  "},
        { "ID": 541 ,  "Topic": "/Jobs & Education/Education/Open Online Courses  "},
        { "ID": 542 ,  "Topic": "/Jobs & Education/Education/Primary & Secondary Schooling (K-12) "},
        { "ID": 543 ,  "Topic": "/Jobs & Education/Education/Private Tutoring Services"},
        { "ID": 544 ,  "Topic": "/Jobs & Education/Education/School Supplies & Classroom Equipment"},
        { "ID": 234 ,  "Topic": "/Jobs & Education/Education/Standardized & Admissions Tests  "},
        { "ID": 545 ,  "Topic": "/Jobs & Education/Education/Study Abroad "},
        { "ID": 546 ,  "Topic": "/Jobs & Education/Education/Visual Arts & Design Education"},
        { "ID": 547 ,  "Topic": "/Jobs & Education/Internships"},
        { "ID": 236 ,  "Topic": "/Jobs & Education/Jobs"},
        { "ID": 237 ,  "Topic": "/Jobs & Education/Jobs/Career Resources & Planning"},
        { "ID": 238 ,  "Topic": "/Jobs & Education/Jobs/Job Listings  "},
        { "ID": 548 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Accounting & Finance Jobs"},
        { "ID": 549 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Clerical & Administrative Jobs"},
        { "ID": 550 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Education Jobs"},
        { "ID": 551 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Executive & Management Jobs  "},
        { "ID": 552 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Government & Public Sector Jobs  "},
        { "ID": 553 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Health & Medical Jobs"},
        { "ID": 554 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/IT & Technical Jobs  "},
        { "ID": 555 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Legal Jobs"},
        { "ID": 556 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Retail Jobs  "},
        { "ID": 557 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Sales & Marketing Jobs"},
        { "ID": 558 ,  "Topic": "/Jobs & Education/Jobs/Job Listings/Temporary & Seasonal Jobs"},
        { "ID": 559 ,  "Topic": "/Jobs & Education/Jobs/Resumes & Portfolios  "},
        { "ID": 239 ,  "Topic": "/Law & Government"},
        { "ID": 560 ,  "Topic": "/Law & Government/Labor & Employment Law "},
        { "ID": 242 ,  "Topic": "/Law & Government/Legal Services "},
        { "ID": 243 ,  "Topic": "/News"},
        { "ID": 561 ,  "Topic": "/News/Business News  "},
        { "ID": 245 ,  "Topic": "/News/Local News "},
        { "ID": 247 ,  "Topic": "/News/Politics"},
        { "ID": 249 ,  "Topic": "/News/World News "},
        { "ID": 250 ,  "Topic": "/Online Communities  "},
        { "ID": 253 ,  "Topic": "/Online Communities/Social Networks  "},
        { "ID": 254 ,  "Topic": "/People & Society"},
        { "ID": 562 ,  "Topic": "/People & Society/Charity & Philanthropy "},
        { "ID": 258 ,  "Topic": "/People & Society/Parenting  "},
        { "ID": 259 ,  "Topic": "/People & Society/Parenting/Adoption "},
        { "ID": 260 ,  "Topic": "/People & Society/Parenting/Babies & Toddlers"},
        { "ID": 563 ,  "Topic": "/People & Society/Parenting/Child Care"},
        { "ID": 263 ,  "Topic": "/Pets & Animals  "},
        { "ID": 264 ,  "Topic": "/Pets & Animals/Pet Food & Pet Care Supplies "},
        { "ID": 265 ,  "Topic": "/Pets & Animals/Pets "},
        { "ID": 267 ,  "Topic": "/Pets & Animals/Pets/Cats"},
        { "ID": 268 ,  "Topic": "/Pets & Animals/Pets/Dogs"},
        { "ID": 272 ,  "Topic": "/Real Estate "},
        { "ID": 564 ,  "Topic": "/Real Estate/Property Development"},
        { "ID": 565 ,  "Topic": "/Real Estate/Real Estate Listings"},
        { "ID": 566 ,  "Topic": "/Real Estate/Real Estate Listings/Commercial Properties  "},
        { "ID": 567 ,  "Topic": "/Real Estate/Real Estate Listings/Residential Rentals"},
        { "ID": 568 ,  "Topic": "/Real Estate/Real Estate Listings/Residential Rentals/Furnished Rentals  "},
        { "ID": 569 ,  "Topic": "/Real Estate/Real Estate Listings/Residential Sales  "},
        { "ID": 570 ,  "Topic": "/Real Estate/Real Estate Services"},
        { "ID": 571 ,  "Topic": "/Real Estate/Real Estate Services/Property Inspections & Appraisals  "},
        { "ID": 289 ,  "Topic": "/Shopping"},
        { "ID": 572 ,  "Topic": "/Shopping/Apparel"},
        { "ID": 573 ,  "Topic": "/Shopping/Apparel/Apparel Services"},
        { "ID": 574 ,  "Topic": "/Shopping/Apparel/Athletic Apparel"},
        { "ID": 575 ,  "Topic": "/Shopping/Apparel/Casual Apparel "},
        { "ID": 576 ,  "Topic": "/Shopping/Apparel/Casual Apparel/T-Shirts"},
        { "ID": 291 ,  "Topic": "/Shopping/Apparel/Children's Clothing"},
        { "ID": 577 ,  "Topic": "/Shopping/Apparel/Clothing Accessories"},
        { "ID": 578 ,  "Topic": "/Shopping/Apparel/Clothing Accessories/Gems & Jewelry"},
        { "ID": 579 ,  "Topic": "/Shopping/Apparel/Clothing Accessories/Gems & Jewelry/Rings  "},
        { "ID": 580 ,  "Topic": "/Shopping/Apparel/Clothing Accessories/Handbags & Purses "},
        { "ID": 581 ,  "Topic": "/Shopping/Apparel/Clothing Accessories/Socks & Hosiery"},
        { "ID": 582 ,  "Topic": "/Shopping/Apparel/Clothing Accessories/Watches"},
        { "ID": 294 ,  "Topic": "/Shopping/Apparel/Costumes"},
        { "ID": 583 ,  "Topic": "/Shopping/Apparel/Eyewear"},
        { "ID": 584 ,  "Topic": "/Shopping/Apparel/Eyewear/Sunglasses "},
        { "ID": 585 ,  "Topic": "/Shopping/Apparel/Footwear"},
        { "ID": 586 ,  "Topic": "/Shopping/Apparel/Footwear/Athletic Shoes"},
        { "ID": 587 ,  "Topic": "/Shopping/Apparel/Footwear/Boots "},
        { "ID": 588 ,  "Topic": "/Shopping/Apparel/Footwear/Casual Shoes  "},
        { "ID": 589 ,  "Topic": "/Shopping/Apparel/Formal Wear"},
        { "ID": 590 ,  "Topic": "/Shopping/Apparel/Headwear"},
        { "ID": 296 ,  "Topic": "/Shopping/Apparel/Men's Clothing "},
        { "ID": 591 ,  "Topic": "/Shopping/Apparel/Outerwear  "},
        { "ID": 592 ,  "Topic": "/Shopping/Apparel/Pants & Shorts "},
        { "ID": 593 ,  "Topic": "/Shopping/Apparel/Shirts & Tops  "},
        { "ID": 594 ,  "Topic": "/Shopping/Apparel/Sleepwear  "},
        { "ID": 595 ,  "Topic": "/Shopping/Apparel/Suits & Business Attire"},
        { "ID": 596 ,  "Topic": "/Shopping/Apparel/Swimwear"},
        { "ID": 597 ,  "Topic": "/Shopping/Apparel/Undergarments  "},
        { "ID": 598 ,  "Topic": "/Shopping/Apparel/Uniforms & Workwear"},
        { "ID": 298 ,  "Topic": "/Shopping/Apparel/Women's Clothing"},
        { "ID": 599 ,  "Topic": "/Shopping/Apparel/Women's Clothing/Dresses"},
        { "ID": 600 ,  "Topic": "/Shopping/Apparel/Women's Clothing/Skirts"},
        { "ID": 293 ,  "Topic": "/Shopping/Coupons & Discount Offers  "},
        { "ID": 601 ,  "Topic": "/Shopping/Gifts & Special Event Items"},
        { "ID": 295 ,  "Topic": "/Shopping/Gifts & Special Event Items/Flowers"},
        { "ID": 297 ,  "Topic": "/Shopping/Gifts & Special Event Items/Party & Holiday Supplies"},
        { "ID": 602 ,  "Topic": "/Shopping/Luxury Goods"},
        { "ID": 603 ,  "Topic": "/Shopping/Mass Merchants & Department Stores "},
        { "ID": 604 ,  "Topic": "/Shopping/Photo & Video Services "},
        { "ID": 605 ,  "Topic": "/Shopping/Photo & Video Services/Event & Studio Photography  "},
        { "ID": 606 ,  "Topic": "/Shopping/Photo & Video Services/Photo Printing Services "},
        { "ID": 607 ,  "Topic": "/Shopping/Product Reviews & Price Comparisons"},
        { "ID": 608 ,  "Topic": "/Shopping/Toys"},
        { "ID": 299 ,  "Topic": "/Sports  "},
        { "ID": 300 ,  "Topic": "/Sports/American Football"},
        { "ID": 301 ,  "Topic": "/Sports/Australian Football  "},
        { "ID": 303 ,  "Topic": "/Sports/Baseball "},
        { "ID": 304 ,  "Topic": "/Sports/Basketball"},
        { "ID": 609 ,  "Topic": "/Sports/Combat Sports"},
        { "ID": 309 ,  "Topic": "/Sports/Cricket  "},
        { "ID": 310 ,  "Topic": "/Sports/Cycling  "},
        { "ID": 315 ,  "Topic": "/Sports/Golf "},
        { "ID": 317 ,  "Topic": "/Sports/Hockey"},
        { "ID": 610 ,  "Topic": "/Sports/Motor Sports "},
        { "ID": 321 ,  "Topic": "/Sports/Olympics "},
        { "ID": 322 ,  "Topic": "/Sports/Rugby"},
        { "ID": 323 ,  "Topic": "/Sports/Running & Walking"},
        { "ID": 325 ,  "Topic": "/Sports/Soccer"},
        { "ID": 611 ,  "Topic": "/Sports/Sporting Goods"},
        { "ID": 612 ,  "Topic": "/Sports/Sporting Goods/Baseball & Softball Equipment "},
        { "ID": 613 ,  "Topic": "/Sports/Sporting Goods/Golf Equipment"},
        { "ID": 614 ,  "Topic": "/Sports/Sporting Goods/Hockey Equipment  "},
        { "ID": 615 ,  "Topic": "/Sports/Sporting Goods/Skateboarding Equipment"},
        { "ID": 616 ,  "Topic": "/Sports/Sporting Goods/Soccer Equipment  "},
        { "ID": 617 ,  "Topic": "/Sports/Sporting Goods/Squash & Racquetball Equipment"},
        { "ID": 618 ,  "Topic": "/Sports/Sporting Goods/Water Sports Equipment"},
        { "ID": 619 ,  "Topic": "/Sports/Sporting Goods/Winter Sports Equipment"},
        { "ID": 328 ,  "Topic": "/Sports/Tennis"},
        { "ID": 620 ,  "Topic": "/Sports/Water Sports "},
        { "ID": 327 ,  "Topic": "/Sports/Water Sports/Swimming"},
        { "ID": 621 ,  "Topic": "/Sports/Winter Sports"},
        { "ID": 324 ,  "Topic": "/Sports/Winter Sports/Skiing & Snowboarding  "},
        { "ID": 332 ,  "Topic": "/Travel & Transportation "},
        { "ID": 334 ,  "Topic": "/Travel & Transportation/Air Travel  "},
        { "ID": 345 ,  "Topic": "/Travel & Transportation/Beaches & Islands"},
        { "ID": 335 ,  "Topic": "/Travel & Transportation/Business Travel "},
        { "ID": 336 ,  "Topic": "/Travel & Transportation/Car Rentals "},
        { "ID": 337 ,  "Topic": "/Travel & Transportation/Cruises & Charters  "},
        { "ID": 338 ,  "Topic": "/Travel & Transportation/Family Travel"},
        { "ID": 340 ,  "Topic": "/Travel & Transportation/Hotels & Accommodations "},
        { "ID": 622 ,  "Topic": "/Travel & Transportation/Hotels & Accommodations/Vacation Rentals & Short-Term Stays "},
        { "ID": 341 ,  "Topic": "/Travel & Transportation/Long Distance Bus & Rail"},
        { "ID": 343 ,  "Topic": "/Travel & Transportation/Luggage & Travel Accessories"},
        { "ID": 623 ,  "Topic": "/Travel & Transportation/Luggage & Travel Accessories/Backpacks & Utility Bags"},
        { "ID": 624 ,  "Topic": "/Travel & Transportation/Luxury Travel"},
        { "ID": 625 ,  "Topic": "/Travel & Transportation/Mountain & Ski Resorts  "},
        { "ID": 626 ,  "Topic": "/Travel & Transportation/Travel Agencies & Services  "},
        { "ID": 627 ,  "Topic": "/Travel & Transportation/Travel Agencies & Services/Guided Tours & Escorted Vacations"},
        { "ID": 628 ,  "Topic": "/Travel & Transportation/Travel Agencies & Services/Sightseeing Tours"},
        { "ID": 629 ,  "Topic": "/Travel & Transportation/Travel Agencies & Services/Vacation Offers  "},
    ];        
      


    const getRandomTopic = () => topics[Math.floor(Math.random() * topics.length)];
  
    const result = [];

    for (let i = 0; i < 3; i++) { // chrome returns 3 topics
        const randomTopic = getRandomTopic();

        result.push({
            "value": randomTopic.ID,
            "taxonomyVersion": "1",
            "modelVersion": "2"
        });
    }

    return result;
};

// Example usage
const browsingTopicsResult = document.browsingTopics();
console.log(browsingTopicsResult);

}
  
// Inject the function into the webpage
var script = document.createElement('script');
script.textContent = '(' + browsingTopics + ')();';
(document.head || document.documentElement).appendChild(script);
script.parentNode.removeChild(script);
